class ProductSeeder
  def self.seed(out = STDOUT)
    Product.create!(:name => "Baked Goods")
    Product.create!(:name => "Cheese")
    Product.create!(:name => "Crafts")
    Product.create!(:name => "Flowers")
    Product.create!(:name => "Eggs")
    Product.create!(:name => "Seafood")
    Product.create!(:name => "Herbs")
    Product.create!(:name => "Vegetables")
    Product.create!(:name => "Honey")
    Product.create!(:name => "Jams")
    Product.create!(:name => "Maple")
    Product.create!(:name => "Meat")
    Product.create!(:name => "Nursery")
    Product.create!(:name => "Nuts")
    Product.create!(:name => "Plants")
    Product.create!(:name => "Poultry")
    Product.create!(:name => "Prepared")
    Product.create!(:name => "Soap")
    Product.create!(:name => "Trees")
    Product.create!(:name => "Wine")
  end
end
